"""Stage a PhoWhisper checkpoint into the source tree so PyInstaller can bundle it.

Run at build time. The shipped app then transcribes with no network access and no
first-use download.

Config and tokenizer files are copied verbatim from the Hub rather than
regenerated by save_pretrained: which files that writes has changed between
transformers major versions, and a missing preprocessor_config.json only shows up
as a failure on a user's machine.

Weights are re-saved as float16, which halves what goes into the .dmg. Inference
still runs in float32 — float16 on MPS produces NaNs with Whisper.

  PHOWHISPER_BUNDLE_MODEL=vinai/PhoWhisper-small python packaging/fetch_model.py
  PHOWHISPER_BUNDLE_FP16=0   # keep full precision instead
"""
import os
import shutil
import sys

REPO = os.environ.get("PHOWHISPER_BUNDLE_MODEL", "vinai/PhoWhisper-small")
USE_FP16 = os.environ.get("PHOWHISPER_BUNDLE_FP16", "1") != "0"

SRC_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEST_ROOT = os.path.join(SRC_DIR, "models")

# Everything the pipeline needs except the weights, which are written separately
# so exactly one copy ends up in the bundle.
CONFIG_PATTERNS = ["*.json", "*.txt", "*.model", "*.jinja"]
WEIGHT_SUFFIXES = (".safetensors", ".bin", ".pt", ".h5", ".msgpack", ".ckpt")


def dir_size_mb(path):
    total = 0
    for root, _, files in os.walk(path):
        for name in files:
            total += os.path.getsize(os.path.join(root, name))
    return total / (1024 * 1024)


def main():
    import torch
    from huggingface_hub import snapshot_download
    from transformers import WhisperForConditionalGeneration

    token = os.getenv("HF_TOKEN") or None

    # Must match app_paths.bundled_model_dir()'s naming, or the app will not find
    # what we stage here and will silently fall back to downloading.
    dest = os.path.join(DEST_ROOT, REPO.replace("/", "__"))
    if os.path.isdir(dest):
        shutil.rmtree(dest)
    os.makedirs(dest, exist_ok=True)

    print(f"==> Copying config and tokenizer files from {REPO}")
    snapshot_download(
        REPO,
        local_dir=dest,
        allow_patterns=CONFIG_PATTERNS,
        token=token,
    )
    # snapshot_download leaves its own bookkeeping directory behind; it would
    # otherwise be copied into the bundle.
    hub_cache = os.path.join(dest, ".cache")
    if os.path.isdir(hub_cache):
        shutil.rmtree(hub_cache)

    staged = sorted(f for f in os.listdir(dest) if not f.startswith("."))
    print(f"    {len(staged)} files: {', '.join(staged)}")
    if "preprocessor_config.json" not in staged:
        print("ERROR: preprocessor_config.json is absent from the repo snapshot")
        return 1

    print(f"==> Loading weights")
    model = WhisperForConditionalGeneration.from_pretrained(REPO, token=token)
    if USE_FP16:
        print("    converting to float16")
        model = model.half()
    model.save_pretrained(dest, safe_serialization=True)

    # snapshot_download may have brought a weight file too if the repo stores it
    # as .bin; drop anything that is not the safetensors we just wrote so the
    # bundle does not carry two copies.
    kept = []
    for name in os.listdir(dest):
        path = os.path.join(dest, name)
        if not os.path.isfile(path) or not name.endswith(WEIGHT_SUFFIXES):
            continue
        if name.endswith(".safetensors"):
            kept.append(name)
        else:
            print(f"    removing duplicate weights: {name}")
            os.remove(path)
    if not kept:
        print("ERROR: no safetensors weight file was written")
        return 1

    # Load exactly what will ship and run it. A missing config file or a broken
    # fp16 conversion fails here instead of on a user's Mac. This is not a proof
    # of offline operation — huggingface_hub reads HF_HUB_OFFLINE at import time
    # and transformers is already imported. The bundle's --selftest-transcribe
    # sets that flag before any import and is what actually proves it.
    print("==> Verifying the staged model loads and runs")
    try:
        import numpy as np
        from transformers import pipeline

        pipe = pipeline(
            "automatic-speech-recognition",
            model=dest,
            torch_dtype=torch.float32,
            # Forced to CPU: the macOS CI runner reports mps as available but
            # cannot actually allocate on it ("MPS allocated: 0 bytes"). This
            # step checks the staged files, not the compute backend.
            device="cpu",
        )
        # One second of near-silence: we are checking that inference executes,
        # not what it says.
        result = pipe(np.zeros(16000, dtype=np.float32))
        print(f"    pipeline ran, returned {result.get('text', '')!r}")
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"ERROR: staged model is not usable: {type(e).__name__}: {e}")
        return 1

    print(f"==> Staged {dir_size_mb(dest):.0f} MB to {dest}")
    print(f"    weights: {', '.join(kept)}")
    print(f"    torch {torch.__version__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
