# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the macOS and Windows builds.

One spec for both: the dependency graph is identical, and the platforms diverge
only at the last step — macOS wraps the collected directory in a .app, Windows
hands it to Inno Setup as-is.

Deliberately onedir, not onefile: the torch payload is well over a gigabyte and
onefile would re-extract all of it into a temp directory on every launch.
"""
import os
import sys

IS_MAC = sys.platform == "darwin"
IS_WINDOWS = sys.platform == "win32"

from PyInstaller.utils.hooks import (
    collect_all,
    collect_dynamic_libs,
    collect_submodules,
    copy_metadata,
)

SPEC_DIR = os.path.dirname(os.path.abspath(SPEC))
SRC_DIR = os.path.abspath(os.path.join(SPEC_DIR, os.pardir))
VERSION = os.environ.get("APP_VERSION", "1.0.0")

datas = [(os.path.join(SRC_DIR, "templates"), "templates")]

# App icon, served as the page favicon at runtime. Generated by
# packaging/make_icon.py; packaging/ itself is build-time only and is not shipped.
STATIC_DIR = os.path.join(SRC_DIR, "static")
if os.path.isdir(STATIC_DIR):
    datas.append((STATIC_DIR, "static"))

# Speech model weights staged by packaging/fetch_model.py. Bundling them is what
# lets the app transcribe offline with no first-use download; without this step
# the directory is simply absent and the app falls back to downloading.
MODELS_DIR = os.path.join(SRC_DIR, "models")
if os.path.isdir(MODELS_DIR):
    datas.append((MODELS_DIR, "models"))
    print(f"spec: bundling models from {MODELS_DIR}")
else:
    print("spec: WARNING - no models/ directory; the app will download on first use")

binaries = []
hiddenimports = [
    "app_paths",
    "settings",
    "web",
    "transcriber",
    "summarizer",
]

# Packages whose contents are resolved dynamically at runtime and so are invisible
# to PyInstaller's import graph.
for pkg in (
    "safetensors",
    "huggingface_hub",
    "soundfile",
    # Gemini SDK: writes the meeting minutes and runs topic tracking.
    "google.genai",
):
    pkg_datas, pkg_binaries, pkg_hidden = collect_all(pkg)
    datas += pkg_datas
    binaries += pkg_binaries
    hiddenimports += pkg_hidden

# The speech engine, plus whatever it pulls in. torchaudio is its likely audio
# backend. Optional so a missing one fails the runtime selftest rather than the
# whole build, which makes the cause obvious in CI.
#
# transformers is deliberately absent. Collecting it dragged in several hundred
# megabytes of unused model architectures, and nothing needs it now that the
# Whisper engine is gone. If chunkformer imports it, PyInstaller's own hook
# collects the parts actually reached.
for pkg in ("chunkformer", "torchaudio"):
    try:
        pkg_datas, pkg_binaries, pkg_hidden = collect_all(pkg)
        datas += pkg_datas
        binaries += pkg_binaries
        hiddenimports += pkg_hidden
        print(f"spec: collected {pkg}")
    except Exception as e:
        print(f"spec: WARNING - could not collect {pkg}: {e}")

# torch is handled by the bundled pyinstaller-hooks-contrib hook; collect_all on
# it roughly triples build time for no gain. Its dylibs are re-collected here
# only as a safety net.
binaries += collect_dynamic_libs("torch")

# uvicorn[standard] selects its event loop and protocol implementations by name.
hiddenimports += collect_submodules("uvicorn")
hiddenimports += [
    "httptools",
    "websockets",
    "websockets.legacy",
    "websockets.legacy.server",
]
# uvloop has no Windows wheel; uvicorn falls back to the asyncio loop there.
if not IS_WINDOWS:
    hiddenimports.append("uvloop")

# The native window. pywebview, pythonnet and pyobjc all register their own
# PyInstaller hooks through the pyinstaller40 entry point, so the WebView2 DLLs
# under webview/lib, the CLR runtime and the PyObjC framework bindings come
# along on their own. Only the backend modules need naming: pywebview picks one
# at runtime by string, which leaves nothing for the import graph to follow.
if IS_WINDOWS:
    hiddenimports += [
        "webview.platforms.winforms",
        "webview.platforms.edgechromium",
        "clr",
    ]

if IS_MAC:
    # objc is named on its own because launcher.py imports it directly, to add
    # the microphone permission handler pywebview's cocoa backend lacks.
    hiddenimports += [
        "webview.platforms.cocoa",
        "objc",
        "Foundation",
        "AppKit",
        "WebKit",
        "Quartz",
    ]

# transformers and huggingface_hub gate features on installed package versions via
# importlib.metadata, which needs the dist-info directories present.
for dist in (
    "torch",
    "transformers",
    "tokenizers",
    "huggingface_hub",
    "safetensors",
    "numpy",
    "regex",
    "requests",
    "tqdm",
    "filelock",
    "packaging",
    "pyyaml",
    "fsspec",
    "openai",
    "google-genai",
    "chunkformer",
    "torchaudio",
):
    try:
        datas += copy_metadata(dist)
    except Exception:
        pass

# Optional heavyweights that transformers probes for but this app never uses.
excludes = [
    "tensorflow",
    "flax",
    "jax",
    "torchvision",
    "matplotlib",
    "numba",
    "llvmlite",
    "librosa",
    "sounddevice",
    "_sounddevice_data",
    "tkinter",
    "PIL",
    "IPython",
    "pytest",
    "notebook",
]

def consolidate_nested_licences(toc, workdir):
    """Fold `*.dist-info/licenses/**` into one text file per distribution.

    torch ships 107 third-party licence files nested up to 182 characters deep
    (…/kineto/libkineto/third_party/dynolog/third_party/prometheus-cpp/3rdparty/
    civetweb/src/third_party/duktape-1.5.2/LICENSE.txt). Windows' 260-character
    path limit makes that unshippable: Inno Setup cannot even open the files to
    compress them, and any install directory more than a few characters longer
    than the default would fail the same way on a user's machine. Flattening the
    names does not help — the depth is in the names themselves.

    Nothing reads these at runtime; importlib.metadata only needs METADATA and
    friends. So concatenate them, headed by their original paths, instead of
    dropping attribution that torch's BSD licence requires us to carry.

    Windows only, deliberately: macOS has no such limit and its build is green.
    """
    marker = ".dist-info/licenses/"
    kept, grouped = [], {}

    for entry in toc:
        dest, src, typecode = entry
        norm = dest.replace("\\", "/")
        idx = norm.find(marker)
        if idx == -1:
            kept.append(entry)
            continue
        dist = norm[:idx].split("/")[-1]
        grouped.setdefault(dist, []).append((norm[idx + len(marker):], src))

    os.makedirs(workdir, exist_ok=True)
    for dist, entries in grouped.items():
        name = f"{dist}-THIRD-PARTY-NOTICES.txt"
        out_path = os.path.join(workdir, name)
        with open(out_path, "w", encoding="utf-8") as out:
            out.write(
                f"Third-party licence notices bundled with {dist}.\n"
                f"Concatenated from {len(entries)} files under "
                f"{dist}.dist-info/licenses/ at build time; the original path of\n"
                f"each precedes its text.\n"
            )
            for rel, src in sorted(entries):
                out.write(f"\n\n{'=' * 78}\n{rel}\n{'=' * 78}\n\n")
                with open(src, "r", encoding="utf-8", errors="replace") as f:
                    out.write(f.read())
        print(f"spec: consolidated {len(entries)} licence files into {name}")
        kept.append((f"licenses/{name}", out_path, "DATA"))

    return kept


a = Analysis(
    [os.path.join(SRC_DIR, "launcher.py")],
    pathex=[SRC_DIR],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

if IS_WINDOWS:
    a.datas = consolidate_nested_licences(
        a.datas, os.path.join(SRC_DIR, "build", "licences")
    )

pyz = PYZ(a.pure)

# Optional: drop an .ico here and the Windows exe and installer pick it up.
ICON_PATH = os.path.join(SPEC_DIR, "icon.ico")
icon = ICON_PATH if (IS_WINDOWS and os.path.isfile(ICON_PATH)) else None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="MeetingSummarizer",
    debug=False,
    bootloader_ignore_signals=False,
    # UPX corrupts torch's shared libraries and breaks code signing.
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="MeetingSummarizer",
)

# Windows stops at COLLECT: dist/MeetingSummarizer/ is what packaging/installer.iss
# turns into a setup.exe. Only macOS needs the extra .app wrapper.
if IS_MAC:
    app = BUNDLE(
        coll,
        name="MeetingSummarizer.app",
        icon=None,
        bundle_identifier="com.tnt.meetingsummarizer",
        version=VERSION,
        info_plist={
            "CFBundleName": "Meeting Summarizer",
            "CFBundleDisplayName": "Meeting Summarizer",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
            "LSMinimumSystemVersion": "11.0",
            "NSHighResolutionCapable": True,
            "LSApplicationCategoryType": "public.app-category.productivity",
            # The app itself does not open the mic (the browser does), but
            # declaring it keeps the bundle honest if a native capture path is
            # ever added.
            "NSMicrophoneUsageDescription":
                "Meeting Summarizer ghi âm cuộc họp để tạo transcript và biên bản.",
            "NSAppTransportSecurity": {"NSAllowsLocalNetworking": True},
        },
    )
